// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDYS09nyzOUj_XIF3K1A8wfmpigK1Ha4',
    appId: '1:267696690048:web:d3319ec85ca0b0d6b1a765',
    messagingSenderId: '267696690048',
    projectId: 'harvestguard-ai-323b4',
    authDomain: 'harvestguard-ai-323b4.firebaseapp.com',
    storageBucket: 'harvestguard-ai-323b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxdWLaUJHwYT-FOZNtS0HFXFrZJp4ohDg',
    appId: '1:267696690048:android:acfa8f7aaeff955db1a765',
    messagingSenderId: '267696690048',
    projectId: 'harvestguard-ai-323b4',
    storageBucket: 'harvestguard-ai-323b4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaga2vVx6FtT__0x1cbyctzu34x_lVnaM',
    appId: '1:267696690048:ios:1a8ff17e169b8126b1a765',
    messagingSenderId: '267696690048',
    projectId: 'harvestguard-ai-323b4',
    storageBucket: 'harvestguard-ai-323b4.firebasestorage.app',
    iosBundleId: 'com.example.harvestguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaga2vVx6FtT__0x1cbyctzu34x_lVnaM',
    appId: '1:267696690048:ios:1a8ff17e169b8126b1a765',
    messagingSenderId: '267696690048',
    projectId: 'harvestguard-ai-323b4',
    storageBucket: 'harvestguard-ai-323b4.firebasestorage.app',
    iosBundleId: 'com.example.harvestguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNDYS09nyzOUj_XIF3K1A8wfmpigK1Ha4',
    appId: '1:267696690048:web:c29e9cae199d49b0b1a765',
    messagingSenderId: '267696690048',
    projectId: 'harvestguard-ai-323b4',
    authDomain: 'harvestguard-ai-323b4.firebaseapp.com',
    storageBucket: 'harvestguard-ai-323b4.firebasestorage.app',
  );
}
